"""add due_date and rename done to completed

Revision ID: 0814d8ba6e1b
Revises: 5d838fc87612
Create Date: 2026-03-04 20:47:32.526380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0814d8ba6e1b'
down_revision: Union[str, Sequence[str], None] = '5d838fc87612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    op.add_column('todos', sa.Column('due_date', sa.Date(), nullable=True))
    op.drop_column('todos', 'done')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('done', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
